### ISSUE TITLE
Access ElderSim dataset

### ISSUE THREAD

**Issue by ofir1080** [mintjohnkim/SynAPT#1]
Hi!
Thanks for this awesome work!
A small issue, how di I get ElderSim data? in their official page the drive includes only a PDF file and the procedure is not mentioned.
Thanks!

**Comment by mintjohnkim** [comment]
Thank you,

After reading and singing the PDF, please send a copy to the email address listed at the bottom of this page: 
https://ai4robot.github.io/ElderSim/#
